### ISSUE TITLE
Tech to be used

### ISSUE THREAD

**Issue by Monal5031** [cerebro-iiitv/web-2018#1]
Suggest the techs to be used.
This will contain payment portal too and a place for updating results or related things of the day of techfest
cc: @anshumanv @aashutoshrathi @yashLadha @anjansrivathsav @mohitkyadav @neelanshsahai

**Comment by yashLadha** [comment]
Can we have a meeting today in evening?

**Comment by Monal5031** [comment]
Sure, how about 10.30pm today? Others please reply too

**Comment by anjansrivathsav** [comment]
Done

On 9 Feb 2018 08:14, "Monal Shadi" <notifications@github.com> wrote:

Sure, how about 10.30pm today? Others please reply too

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Techfest-IIITV/Website/issues/1#issuecomment-364318702>,
or mute the thread
